//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSoft.Dynamite.Search.SP.SP.CONTROLTEMPLATES.GSoft.Dynamite.Search {
    
    
    public partial class SocialMetaTags {
        
        /// <summary>
        /// OpenGraphTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSoft.Dynamite.Search.Core.Controls.TemplatedControlWrapper OpenGraphTitle;
        
        /// <summary>
        /// OpenGraphImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSoft.Dynamite.Search.Core.Controls.ImageElementControlWrapper OpenGraphImage;
        
        /// <summary>
        /// OpenGraphUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSoft.Dynamite.Search.Core.Controls.UrlElementControlWrapper OpenGraphUrl;
        
        /// <summary>
        /// OpenGraphDescription control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GSoft.Dynamite.Search.Core.Controls.TemplatedControlWrapper OpenGraphDescription;
    }
}
