//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GSoft.Dynamite.Portal.SP.Publishing.WebParts.ChildNodes {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    
    
    public partial class ChildNodes {
        
        public static implicit operator global::System.Web.UI.TemplateControl(ChildNodes target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__BuildControlTree(global::GSoft.Dynamite.Portal.SP.Publishing.WebParts.ChildNodes.ChildNodes @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<div id=\"");
 @__w.Write(this.UniquePerRequestId );

            @__w.Write(@""" class=""child-nodes"">
    <div class=""nodes"" data-bind=""foreach: Nodes"">
        <div class=""item"">
            <a data-bind=""attr: {href: Url, title: Title}"">
                <div class=""title item-block"">
                    <div class=""inside"">
                        <h3 data-bind=""text: Title""></h3>
                        <div class=""icon icon-arrow-teal""></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

<script>
    var childNodesParams = {};
    childNodesParams.ParentElementId = '");
                                @__w.Write(this.UniquePerRequestId );

            @__w.Write("\';\r\n    childNodesParams.RawChildNodes = ");
                             @__w.Write(this.NodesJSON );

            @__w.Write(";\r\n    GSoft.Dynamite.Portal.ChildNodes.initialize(childNodesParams);\r\n</script>\r" +
                    "\n");
        }
        
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
